### ISSUE TITLE
Unsupported platform windows amd64 for version latest

### ISSUE THREAD

**Issue by ghost** [browser-actions/setup-firefox#252]
### I started a Github Actions workflow with the following job setup:
```
jobs:
  local:
    runs-on: windows-latest
...
  steps:
  - name: Setup Firefox
    uses: browser-actions/setup-firefox@v0.0.0
```

### But run fails with the message:

```
Run browser-actions/setup-firefox@v0.0.0
  with:
Setup firefox latest (en-US)
Attempting to download firefox latest...
Error: Unsupported platform windows amd64 for version latest
```

**Comment by kriegaex** [comment]
Why did nobody react to this issue for two months? This GitHub action is kind of pointless if it does not work on GitHub with the frequently used `runs-on: windows-latest`.

```yml
- name: Set up Firefox browser
  if: ${{ matrix.gebEnv == 'firefox_headless' }}
  uses: browser-actions/setup-firefox@latest
  with:
    firefox-version: latest
```

```none
Run browser-actions/setup-firefox@latest
  with:
    firefox-version: latest
  env:
    JAVA_HOME: C:\hostedtoolcache\windows\Java_Adopt_jdk\8.0.3[2](https://github.com/kriegaex/GebSpockSamples/runs/5268342287?check_suite_focus=true#step:7:2)2-6\x6[4](https://github.com/kriegaex/GebSpockSamples/runs/5268342287?check_suite_focus=true#step:7:4)
Setup firefox latest (en-US)
Attempting to download firefox latest...
Error: Unsupported platform windows amd[6](https://github.com/kriegaex/GebSpockSamples/runs/5268342287?check_suite_focus=true#step:7:6)4 for version latest
```
