### ISSUE TITLE
Getting error Error: The process '/__t/firefox/latest/x64/firefox' failed with exit code 1

### ISSUE THREAD

**Issue by faith-berroya** [browser-actions/setup-firefox#518]
Hello I'm currently trying to run our Selenium Tests in Firefox only. I keep trying to use `browser-actions/setup-firefox@latest` but it's giving me the error below:
<img width="1394" alt="image" src="https://github.com/browser-actions/setup-firefox/assets/101372793/62bfa948-bf00-414f-9920-8e2e79509cb9">
I was able to install `browser-actions/setup-geckodriver@latest` but not Firefox. 
Below is my full `.yml` file. Please let me know if I am missing something. Thank you!

```
name: Create Selenium Scheduled Workflow

on:
  schedule:
    - cron: '0 10 * * 1,4'
  push:
    branches: [ master ]

jobs:
  downloadCoursesAndEmbeddingH5PMedia:
    runs-on: ubuntu-latest
    environment: release
    container:
        image: python:latest
    strategy:
        matrix:
            firefox: [ 'latest' ]
    steps:
    - shell: bash
      run: apt-get update
    - shell: bash
      run: |
        DEBIAN_FRONTEND=noninteractive apt-get install -y \
          libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb \
          binutils \
          fonts-ipafont fonts-ipaexfont
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - uses: browser-actions/setup-geckodriver@latest
    - run: geckodriver --version
    # - uses: browser-actions/setup-firefox@latest
    # - run: firefox --version
    - name: Prepare Firefox
      uses: browser-actions/setup-firefox@latest
    - name: Firefox version
      run: firefox --version
    - name: run feature file
      run: behave "features/firstFeature.feature" "features/secondFeature.feature"
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Create Selenium artifacts
        path: ./cypress/videos/**.feature.mp4
```
